services:
  ordermanager.api:
    image: ${DOCKER_REGISTRY-}ordermanagerapi
    build:
      context: .
      dockerfile: OrderManager.API/Dockerfile
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432" # Expose PostgreSQL on localhost:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data in a named volume
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Port for RabbitMQ client connections
      - "15672:15672" # Port for RabbitMQ management interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest 

volumes:
  postgres-data:
    driver: local